const jwt = require('jsonwebtoken');


const jsonTokenCreate = async (data) => {
    try {
        const {email, _id} = data;
        return jwt.sign({id: _id, email: email}, process.env.JWT_SECRET, {expiresIn: '1d'});
    }catch(err) {
        console.error("token is not generated by json web token")
        throw err;
    }
}

const tokenVerify = async (token) => {
    try{
        return await jwt.verify(token, process.env.JWT_SECRET);
    }catch(err) {
        console.error("token is not verify issue", err)
        throw err;
    }
}

module.exports = {jsonTokenCreate,tokenVerify};