const jwt = require('jsonwebtoken');


const jsonTokenCreate = async (data) => {
    try {
        const {email, _id, name, image} = data;
        return jwt.sign({id: _id, email: email, name: name, image: image}, process.env.JWT_SECRET, {expiresIn: '1d'});
    } catch (err) {
        console.error("token is not generated by json web token")
        throw err;
    }
}

const tokenVerify = async (token) => {
    try {
        if (!token) {
            console.log('token verify failed')
            return null;
        }
        return await jwt.verify(token, process.env.JWT_SECRET);
    } catch (err) {
        console.error("token is not verify issue")
        throw err;
    }
}

module.exports = {jsonTokenCreate, tokenVerify};